### ISSUE TITLE
[cloud-run-django]:

### ISSUE THREAD

**Issue by acecpt** [googlecodelabs/feedback#1055]
in the Django walkthrough, it starts with CloudShell: https://codelabs.developers.google.com/codelabs/cloud-run-django#1
on Terminal/CLI; 
then when we switch to cloudshell edit: https://codelabs.developers.google.com/codelabs/cloud-run-django#5 on the IDE & Terminal/CLI, all of the BASH variables get wiped and have to be redeclaired. also, on the terminal reset, you have to cd back into the ~home/user/myproject directory from the ~home/user/ starting point to get the requirements.txt and other things at the right structure.  At the very least all the BASH variables having to be restated caused me hours of pain and a full reset of the project

Still not successful yet (on step 8), but figured I should share to drive up adoption of CloudRun

**Comment by acecpt** [comment]
I had to re-declare $PROJECT_ID; $REGION; $GS_BUCKET_NAME; $DATABSE_URL; $PROJECTNUM; $CLOUDRUN

**Comment by acecpt** [comment]
failing on build in step 8 to initialize the docker image because "pip install Django" in step 4 doesn't include "pip install django-environ'' - restarting build for 4th time to include pip install django-environ in requirements.txt in step 4. I see it's at the bottom in step 6 requirements.txt - btw, django-environ is now 0.8.1 - and pylint wasn't resolving it in settings.py of prior build attempt

**Comment by acecpt** [comment]
build finally worked by adding django-environ right after apt install django and upgrading the version on googl-auth and google-coud-secret-manager

**Comment by acecpt** [comment]
got terraform working too now. can do GET, but fail on CSRF for PUT; just like this: https://stackoverflow.com/questions/70399440/cloudrun-djangoterraform-404-error-on-app-url

@craiglabenz @ViMonks any ideas? is it down to the CSRF token being in the env.tpl / Secret Manager ?

**Comment by glasnt** [comment]
> changing to cloudshell edit

You should be able to swap between edit and terminal at any time by clicking "Open Editor"/"Open Terminal". Opening a new terminal in Cloud Shell Editor or a new tab in Cloud Shell will reset any terminal specific variables. 

> requirements

This tutorial specifically builds from the Django template startproject for freshness and yes, step 6 adds the settings.py and requirements.txt changes to drive Google Cloud specific changes. 

> pylint wasn't resolving

pylint is driven from the selected python interpreter, which won't know of custom dependencies unless they have been installed into the environment for that specific interpreter. google-cloud-storage may be already available in a Cloud Shell environment, so that package doesn't error, but django-environ may. 

> fail on CSRF

You will need to use the new change in the settings.py in the codelab to handle CSRF changes in Django 4.0. 

In step 5 the settings.py includes:

```
# If defined, add service URL to Django security settings
CLOUDRUN_SERVICE_URL = env("CLOUDRUN_SERVICE_URL", default=None)
if CLOUDRUN_SERVICE_URL:
    ALLOWED_HOSTS = [urlparse(CLOUDRUN_SERVICE_URL).netloc]
    CSRF_TRUSTED_ORIGINS = [CLOUDRUN_SERVICE_URL]
else:
    ALLOWED_HOSTS = ["*"]
```

Step 9 shows how to add `CLOUDRUN_SERVICE_URL` to your secrets and update them.
