### ISSUE TITLE
[cloud-video-intelligence-python3] - Useless service at the moment

### ISSUE THREAD

**Issue by ollyde** [googlecodelabs/feedback#1205]
The service is fairly useless at the moment because there's no way to pub-sub it.

CloudRun for example has a 15 minute timeout for example, that's one of the longer ones.
Many of the videos we test go over 15 minutes.

**Comment by PicardParis** [comment]
Hi Oliver / @ollyde,
Thanks for your feedback, I'll improve the codelab asap. The codelab's goal is to show how to quickly use the client library features (with short video processing operations). I understand that the use of `operation.result()` (waiting synchronously for a short operation) can be misleading. A few remarks:
- If you'd like to process a video analysis, you don't need to wait for the analysis to complete synchronously. You'd rather work asynchronously by specifying an output bucket, not wait for the operation (i.e. you'd just call `video_client.annotate_video(request)` and exit) but plug events to be notified and use the results when they're ready.
- Here is an example article/architecture using 3 buckets to trigger Cloud Functions in a processing pipeline:
  - https://github.com/PicardParis/private-cherry-on-py/tree/main/gcf_video_summary#-architecture
  - ![screenshot](https://raw.githubusercontent.com/PicardParis/cherry-on-py-pics/main/gcf_video_summary/pics/architecture_1.png)
- In this example, Cloud Storage events are directly triggering serverless services (Cloud Functions here, could be Cloud Run), but you can also plug them to a Pub/Sub channel instead:
  - [Pub/Sub notifications for Cloud Storage](https://cloud.google.com/storage/docs/pubsub-notifications)
- With such an asynchronous pipeline, you can definitely process videos of [up to 3 hours](https://cloud.google.com/video-intelligence/quotas) (in a cost effective way because resources are used only when actually processing something).
- Note that this is a simple architecture example. Today, I'd probably replace step 2 to have it orchestrated with [Cloud Workflows](https://cloud.google.com/workflows/docs/overview) (benefit: it handle errors and retries).
- Finally, if your analysis processing itself needs more time, you can extend the default timeout (Cloud Run timeout can be extended [up to 60 minutes](https://cloud.google.com/run/docs/configuring/request-timeout)).

Does it provide ways to address your concern? If not, can you provide more details?

**Comment by ollyde** [comment]
@PicardParis we decided to use the new Cloud Run Jobs to run a background process, as we are running cloud video intelligence and video transcoder api (which has pub/sub) in parallel.

We wanted to keep the process simple.
User Uploads files -> [transcoder & video intelligence] -> Update database / Notify client

This works fine for us.

The problem is Cloud Run Jobs (Beta) only allows 1 hour, there seems to be no reason for this limit, it should be able to be anything :-D

**Comment by PicardParis** [comment]
I understand better. The APIs have different designs. To add Video Intelligence calls in parallel, I'd add a bucket to store the video analyses (`output_uri` parameter in the request) and plug Pub/Sub on the `OBJECT_FINALIZE` event. This would prevent having a job wait for variable durations (more cost effective, your job would just take seconds to launch the two parallel processes) + would avoid the timeout issue.

**Comment by ollyde** [comment]
@PicardParis the developer complexity is lower on our approach since it’s just functions inside the main monolith; thanks for the suggestion though will keep it noted and take another look!

**Comment by PicardParis** [comment]
👍 Closing the ticket for now. Feel free to reopen if you have new feedback...

**Comment by PicardParis** [comment]
Just FYI, made an update pass, modified code samples, and added a note regarding synchronous vs asynchronous modes:
- https://codelabs.developers.google.com/codelabs/cloud-video-intelligence-python3
