### ISSUE TITLE
[cloud-text-speech-python3]…

### ISSUE THREAD

**Issue by tobydevey** [googlecodelabs/feedback#1226]
I am following the tutorial and got as far as navigating to the home directory then >
Can't set up virtual environment. get this message in the terminal:
 dest
virtualenv: error: argument dest: the destination . is not write-able at /home
SystemExit: 2

**Comment by PicardParis** [comment]
Hi @tobydevey,
- It looks like you're one folder too high (`/home` is read-only for users).
- Can you first move to your home directory with the following command?
  - `cd ~`
  - If you type `pwd`, this should output `/home/USER`
  - Then you can create the virtual environment

**Comment by tobydevey** [comment]
Thanks PicardParis,
If I navigate tp /home and then pwd
The result is /home
Do I need to create the USER folder?

**Comment by PicardParis** [comment]
You don't need to (and can't because `/home` is read-only) create your username folder. It should be pre-created. Here's a more detailed example:
- Let's assume your username is `tobydevey`
- `cd ~` (not `cd /home`, this may be the source of confusion)
- `pwd`
- This should display `/home/tobydevey`
- Then, you're good to follow the tutorial

`/home/USER` (with USER being your username) is the writable directory created for you by Cloud Shell. If you still get `/home`, you must be in a different environment. In this case, follow the "Setup and requirements" step.

**Comment by tobydevey** [comment]
Thank you. Sorry I've been away for a while but now back to it and all is
working as you said it would.

**Comment by PicardParis** [comment]
Cool. I hope you'll enjoy the tutorial. I'm closing the ticket.
