### ISSUE TITLE
[cloud-app-engine-python3]… 502 bad gateway error

### ISSUE THREAD

**Issue by hyungpil** [googlecodelabs/feedback#1311]
i follow up this page
https://codelabs.developers.google.com/codelabs/cloud-app-engine-python3#5

but failed.

502 bad gateway error occurs.

**Comment by PicardParis** [comment]
Thank you for your feedback. I'll have a look either today if possible or at the end of the week.

**Comment by PicardParis** [comment]
- Thanks a lot for reporting the issue. I'm able to reproduce it.
- This is due to a new dependency issue (Flask package dependency is not well defined // Werkzeug) and is easy to fix. I'll update the codelab asap.
- You can fix the problem by specifying the latest version of Flask:

**`requirements.txt`**
```
# https://pypi.org/project/Flask
Flask==3.0.0
```

**Comment by PicardParis** [comment]
- The lab is up-to-date:
  - https://codelabs.developers.google.com/codelabs/cloud-app-engine-python3
  - Uses `Flask==3.0.0` (enough to fix the issue)
  - Updated to Python 3.12 (`runtime: python312` in `app.yaml`)
- Thanks again for your feedback.
