### ISSUE TITLE
Hello-JNI Tutorial says use Android 2.2 or higher

### ISSUE THREAD

**Issue by pnemere** [googlecodelabs/feedback#28]
On the first page, under "What you'll need":
_"Android Studio version 2.2 or higher, or a version before 2.0 [note: 2.0, 2.1 break certain ndk supports, should avoid]."_

I just uninstalled my 2.1 and went hunting for 2.2... even the canary update channel only goes up to 2.1.1?? Is this a typo?

Also if it's going to state that ndk support is broken, it'd be useful to include a link to a page describing why... or a bit more info about it!

Cheers,

**Comment by x1ddos** [comment]
@ggfan can you take a look, please.

**Comment by ggfan** [comment]
it is not a typo:  android studio automatically generating JNI prototype is broken in android studio 2.0/2.1, it is fixed in 2.2; 2.2 preview soon will be available on canary.  Android Studio 1.5 still work for this codelab.  It is strange situation at the moment... but it is fixed in the next preview ( 2.2 ) and will be pretty soon available on canary

**Comment by ggfan** [comment]
this one is now fixed. Code lab is update with formal release and canary link.
