### ISSUE TITLE
[cloud-hello-istio]: Istio Initializer doesn't exist

### ISSUE THREAD

**Issue by scottefein** [googlecodelabs/feedback#350]
On step 4, very bottom, there's 

`kubectl apply -f install/kubernetes/istio-initializer.yaml`

That file does not exist.

**Comment by kenthua** [comment]
Looks like it was removed in the 0.5.0 release because automatic sidecar injections have totally changed and depend on k8s 1.9+.  For the current instructions and time being will likely need to pull the [0.4.0](https://github.com/istio/istio/releases/tag/0.4.0) release to do the quicklab. 

EDIT 1: note to [reference](https://istio.io/docs/setup/kubernetes/sidecar-injection.html)

EDIT 2: until it gets updated, if you have already run the 0.5.0 auth, you can clean it up by running 
```
kubectl delete -f install/kubernetes/istio-auth.yaml
```
Then download the 0.4.0 and go through the codelab

**Comment by alexismp** [comment]
A new version of the codelab was recently pushed out, updating to Istio 0.5.1

**Comment by meteatamel** [comment]
This bug is not relevant anymore as the instructions are different now. Closing.
