### ISSUE TITLE
[cloud-spring-petclinic-cloudsql]:

### ISSUE THREAD

**Issue by joedayz** [googlecodelabs/feedback#354]
1) If you update your gcloud components you need to change it command:

$ gcloud beta sql instances describe my-instance |grep connectionName

to

$ gcloud beta sql instances describe my-instance |grep connectionName

2) Clone and test the Pet Clinic application locally is confuse. It must to be:

Clone and test the Pet Clinic application in cloud shell.

3)

gcloud sql connect my-instance -u root
Whitelisting your IP for incoming connection for 5 minutes...done.
Enter password: <Press Enter, there is no password by default>

I use ENTER but I am always getting a error.

**Comment by joaoandremartins** [comment]
1) What is the difference in the command? It seems both commands you gave are the same. I tried the command in the codelab and it seems to be working.
2) The Cloud Shell environment is considered "local". You can do the same from your local machine instead of the Cloud Shell.
3) Which error are you getting? Check if you have an IPv6 IP, there used to be an issue connecting to Cloud SQL instances from IPv6 IPs that might still be active.

**Comment by joedayz** [comment]
Sorry Joao. I solved these issues. I am going to close my issue.
