### ISSUE TITLE
Hello-JNI Tutorial APK loads, then crashes at step 4.4

### ISSUE THREAD

**Issue by jurgenrgh** [googlecodelabs/feedback#90]
A "Hello World" app that doesn't run?

**Comment by ggfan** [comment]
step 4.4 is:   Sync , Build , there should be no errors from Android Studio.
if we are at the same step, this step only sync, build, BUT should load apk. It could only Sync and Build, but do NOT load --- the project claimed a native function on java side, but has NOT implementation for it, so it will not run for sure.  If it is in normal c/C++ program it would be an link error; however since java push it at the loading time to check for native shared libs, it will crashes there.

only after the native code implemented, the apk could be loaded.  I will clarify it in Note section for that step;  also the version numbers are not up to date, you would use the latest version numbers for variaous components:
- gradle-experimental plugin version:  https://jcenter.bintray.com/com/android/tools/build/gradle-experimental/ and use the latest one
- SDK / NDK version with latest
- Android studio will prompt for the matching gradle version, just accepting it would be fine
  
  thank you for bring it up.

**Comment by ggfan** [comment]
Sorry, I had a typo in my message, important one:  It should NOT be loaded --  
BUT should load apk  ==>

BUT should NOT load apk

there is no way to load it since: there is NO native lib yet,  next step when adding C file and functions, AS will create the shared lib, then could load on android system.  

If you could not Sync at all, may you put your environment so I could have a look? the versions are not latest, but AS will take care of the upgrading automatically.   thanks
